#!/bin/bash
# Rebuilds the lesson samples from src/jordan-sample.html, a synthetic resume (no real person).
# Needs macOS tools only: Google Chrome (headless), qlmanage, sips, textutil, base64.
#   jordan-sample.docx            text stored as characters in XML
#   jordan-sample-textlayer.pdf   born-digital PDF: Chrome prints the page, so every glyph is in a text layer
#   jordan-sample-flattened.pdf   the same page as one image: zero characters, only OCR can read it
#   samples.js                    base64 copies, so lesson buttons work from file:// without fetch()
set -euo pipefail
cd "$(dirname "$0")"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
SRC="src/jordan-sample.html"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 1. Born-digital PDF (text layer). Headless Chrome is slow to start, so skip it when the PDF is newer than the HTML.
if [ ! -f jordan-sample-textlayer.pdf ] || [ "$SRC" -nt jordan-sample-textlayer.pdf ]; then
  "$CHROME" --headless --disable-gpu --user-data-dir="$TMP/profile" --no-pdf-header-footer \
    --print-to-pdf="$PWD/jordan-sample-textlayer.pdf" "file://$PWD/$SRC" 2>/dev/null
fi

# 2. Flattened PDF: rasterise the text-layer PDF at 192 dpi (1632x2112 px for US Letter), then wrap the
#    pixels in a new PDF. Only the image survives, so the text layer is gone. (Chrome's --screenshot hung here.)
qlmanage -t -s 2112 -o "$TMP" jordan-sample-textlayer.pdf >/dev/null 2>&1
sips -s dpiWidth 192 -s dpiHeight 192 "$TMP/jordan-sample-textlayer.pdf.png" >/dev/null
sips -s format pdf "$TMP/jordan-sample-textlayer.pdf.png" --out jordan-sample-flattened.pdf >/dev/null

# 3. DOCX via macOS textutil (HTML to WordprocessingML).
textutil -convert docx -output jordan-sample.docx "$SRC"

# 4. samples.js for the file inspector.
{
  echo "// Generated by make_samples.sh. Synthetic resume samples, base64-encoded for assets/file-inspector.js."
  echo "window.RESUME_SAMPLES = {"
  for spec in "docx|jordan-sample.docx|DOCX" "textpdf|jordan-sample-textlayer.pdf|Text-layer PDF" "flatpdf|jordan-sample-flattened.pdf|Flattened PDF"; do
    IFS='|' read -r key file label <<<"$spec"
    printf '  %s: { name: "%s", label: "%s", b64: "%s" },\n' "$key" "$file" "$label" "$(base64 -i "$file" | tr -d '\n')"
  done
  echo "};"
} > samples.js

ls -l jordan-sample.docx jordan-sample-textlayer.pdf jordan-sample-flattened.pdf samples.js
